title: Moemeylane's Blog
description: Documenting my journey as a developer
author: Moemeylane
markdown: kramdown

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-remote-theme
